### ISSUE TITLE
Add `create post-review checklist` command to editorialbot

### ISSUE THREAD

**Issue by jgostick** [openjournals/joss#1188]
I started a discussion [on slack](https://openjournals.slack.com/archives/G016161K539/p1675444471238729) about this command and most were in favor.  The idea is that:

```@editorialbot create post-review checklist```

would output the following:

# Post-Review Checklist for Editor and Authors
## Additional Author Tasks After Review is Complete
- [ ] Double check authors and affiliations (including ORCIDs)
- [ ] Make a release of the software with the latest changes from the review and post the version number here. This is the version that will be used in the JOSS paper.  
- [ ] Archive the release on Zenodo/figshare/etc and post the DOI here.
- [ ] Make sure that the title and author list (including ORCIDs) in the archive match those in the JOSS paper.

## Editor Tasks Prior to Acceptance
- [ ] Read the text of the paper and offer comments/corrections (as either a list or a PR)
- [ ] Check the references in the paper for corrections (e.g. capitalization)
- [ ] Set article DOI with ``@editorialbot set <DOI here> as archive``
- [ ] Set version with ``@editorialbot set <version here> as version``
- [ ] Double check rendering of paper with ``@editorialbot generate pdf``
- [ ] Specifically check the references with ``@editorialbot check references`` and ask author(s) to update as needed
- [ ] Do a 'dry run' of acceptance with ``@editorialbot recommend-accept``

**Comment by xuanxu** [comment]
Done and deployed! 
The `@editorialbot create post-review checklist` command should be available to editors now.

**Comment by Kevin-Mattheus-Moerman** [comment]
@xuanxu @jgostick my only comment is that the archive DOI is of course different from the article DOI, so the following: 
- [ ] Set article DOI with `@editorialbot set <DOI here> as archive`

Should be: 
- [ ] Set archive DOI with `@editorialbot set <DOI here> as archive`

**Comment by xuanxu** [comment]
@Kevin-Mattheus-Moerman good catch. Changed!
