### ISSUE TITLE
[Tracking]: Improving the review process

### ISSUE THREAD

**Issue by arfon** [openjournals/joss#159]
As described in https://github.com/openjournals/joss/issues/125, we'd like to streamline JOSS reviews so that:
- Editors can assign reviewers
- We stop spamming reviewers asking for help (i.e. no more `cc @openjournals/joss-reviewers`)
- Our robot `@whedon` can start automating some of these steps

This is a tracking issue that should capture all of the items designed to update the review process. These are the things I think we need to do:
- [x] create a searchable, machine readable form of JOSS reviewers based on their programming background and academic interests: https://gist.github.com/arfon/5317c568cb32c7b917fea3c13958131d
- [x] create a searchable, machine readable form of JOSS editors based on their academic interests: https://gist.github.com/arfon/404b17728e4954f414ddb512f28a8ce0
- [x] modify https://github.com/openjournals/joss to create meta-issue from admin UI (rather than go straight to full JOSS review issue) that is used to assign find/assign reviewer
- [x] turn `@whedon` into a sentient being so he can be asked to make a review issue after a reviewer has been found
- [x] make it possible for `@whedon` to compile the `paper.md` and add it to the review issue (needs error reporting if paper doesn't compile)
- [x] `@whedon` needs to start tracking who is doing reviews/handing editing for papers so we can make sure we're not over-loading folks.

**Comment by arfon** [comment]
@karthik - I've made a bunch of progress on this. Would you be up for helping me test this out a little on http://joss.theoj.org/papers/b89568b89a7b8fd7d0792fcd836ba120 ?
